### ISSUE TITLE
Bank SDK Example App: Amount text field does not accept input

### ISSUE THREAD

**Issue by JohJakob** [gini/gini-mobile-ios#564]
The amount text field in the [Gini Bank SDK example app](https://github.com/gini/gini-mobile-ios/tree/GiniBankSDK%3B3.3.0/BankSDK/GiniBankSDKExample/GiniBankSDKExample) is not accepting any input, neither typed nor pasted.

https://github.com/gini/gini-mobile-ios/assets/9888537/16f9e433-4fe9-432a-98de-da8d36f81ec6

***

## Environment

**Xcode Version**: 15.4
**iOS Version**: 17.5
**macOS Version**: 14.5

**Comment by zladzeyka** [comment]
Hi, 👋 @JohJakob may I ask you what are you testing here with all empty fields?
We don't cover the start flow from the empty screen.

This app is a mock banking app, that is intended for testing Gini Pay Connect starting from the Insurance app. 
After the data is successfully retrieved and prefilled from the payment request you will be able to change the values.
Don't forget to add the credentials to https://github.com/gini/gini-mobile-ios/blob/main/BankSDK/GiniBankSDKExample/GiniBankSDKExampleBank/Credentials.plist

**Comment by JohJakob** [comment]
Hi @zladzeyka, I was trying to test the Gini payment feature in the [ottonova](https://ottonova.de) app (to be more precise, the things that happen after confirming a payment). It does open the Bank SDK example app, but does not pre-fill any payment details.

I am a bit confused because a colleague on the iOS engineering team said that the credentials are not required… but if you say so, I will investigate further.

**Comment by zladzeyka** [comment]
@JohJakob credentials are required, here is the [doc for testing](https://developer.gini.net/gini-mobile-ios/GiniHealthSDK/4.1.0/testing.html) and in the step `Testing` we've mentioned the credentials. 🙏

**Comment by zladzeyka** [comment]
Hopefully, the documentation helped🤞🏻
